on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4
      # setup docker buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # setup metadata
      - name: Setup Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            dummy
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=tag
            type=sha
          flavor: |
            latest=true
      # debug
      - run: |
          echo cwd://${{ steps.meta.outputs.bake-file-tags }}
          echo cwd://${{ steps.meta.outputs.bake-file-labels }}

      # bake
      - name: Build
        uses: docker/bake-action@v6
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file-tags }}
            cwd://${{ steps.meta.outputs.bake-file-labels }}
          targets: build
